businesses/urls.py
from django.urls import path

from . import views

app_name = "businesses"

urlpatterns = [
    path("categories", views.CategoryListView.as_view(), name="categories"),
    path("<str:slug>", views.CategoryDetailView.as_view(), name="category"),
    path(
        "<str:cat_slug>/<str:sub_slug>",
        views.SubCategoryDetailView.as_view(),
        name="subcategory",
    ),
    path(
        "<str:cat_slug>/<str:sub_slug>/<str:biz_slug>",
        views.BusinessDetailView.as_view(),
        name="business",
    ),
]

config/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("businesses/", include("businesses.urls", namespace="businesses")),
    path(
        "admin/" if settings.DEBUG else settings.ADMIN_URL,
        admin.site.urls,
    ),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("send-verification", views.send_email_verification, name="send-verification"),
    path("verify/<str:secret>", views.complete_verification, name="verify"),
    path("login/google", views.google_login, name="google-login"),
    path("login/google/callback", views.google_callback, name="google-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("profile", views.ProfileView.as_view(), name="profile"),
    path("password", views.PasswordUpdateView.as_view(), name="password"),
]

templates/partials/footer.html
<footer>
    <div class="container mx-auto">
        &copy; dmvhanin. All rights reserve.
    </div>
</footer>

templates/partials/header.html
{% load static %}
<header>
    <div class="container mx-auto flex justify-between items-center">
        <div>
            <a href="{% url 'core:home' %}"><img src="{% static 'img/logo2.png' %}"></a>
        </div>
        <div class="main-menu-btn p-2 lg:hidden z-10">
            <i class="fa-solid fa-bars fa-lg menu"></i>
            <i class="fa-solid fa-xmark fa-lg close"></i>
        </div>
        <div class="menu-background fixed hidden inset-0 h-screen w-screen bg-gray-900 opacity-50">
        </div>
        <div class="main-menu fixed lg:static top-0 pt-16 lg:pt-0 -right-full transition-all ease-in-out duration-300 h-screen lg:h-auto w-1/2 md:w-1/3 bg-stone-700 lg:bg-transparent lg:grow lg:flex justify-between">
            <ul class="lg:flex">
                <li><a href="{% url 'businesses:categories' %}" class="nav-link">한인업소록</a></li>
            </ul>
            <hr class="lg:hidden">
            <ul class="lg:flex">
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}" class="nav-link">Admin Site</a></li>
                    {% else %}
                    <li><a href="{% url 'users:profile' %}" class="nav-link">
                        {% if user.nickname %}
                        <b>{{ user.nickname }}</b>님
                        {% else %}
                        닉네임 설정
                        {% endif %}
                    </a></li>
                    {% endif %}
                    <li><a href="{% url 'users:logout' %}" class="nav-link">로그아웃</a></li>
                {% else %}
                <li><a href="{% url 'users:signup' %}" class="nav-link">회원가입</a></li>
                <li><a href="{% url 'users:login' %}" class="nav-link">로그인</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>

<script>
    (() => {
        const header = document.querySelector('header');
        document.querySelector('.main-menu-btn').addEventListener('click', () => {
            header.classList.toggle('show');
        });
        document.querySelector('.menu-background').addEventListener('click', () => {
            header.classList.remove('show');
        });
    })();
</script>

templates/partials/messages.html
{% if messages %}
    <ul class="message-container absolute mx-auto left-0 right-0 flex justify-center">
        {% for message in messages %}
        <li class="message font-medium bg-gray-700 rounded-full z-50 text-white py-4 px-6 w-64 text-center {% if message.tags %}{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/social_login.html
<div class="grid grid-rows-2 md:grid-rows-1 md:grid-cols-2 gap-2 w-full">
    <a href="{% url 'users:google-login' %}{% if 'next' in request.GET %}?next={{ request.GET.next }}{% endif %}" class="btn text-gray-50 bg-red-500 flex items-center justify-center rounded-full">
        <i class="fa-brands fa-google mr-2 font-bold rounded-full text-red-600 bg-gray-50 p-2"></i> 구글 로그인
    </a>
    <a href="{% url 'users:kakao-login' %}{% if 'next' in request.GET %}?next={{ request.GET.next }}{% endif %}" class="btn text-yellow-800 bg-yellow-300 flex items-center justify-center rounded-full">
        <i class="fa-solid fa-comment mr-2 fa-lg"></i> 카카오 로그인
    </a>
</div>

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>