businesses/urls.py
from django.urls import path

from . import views

app_name = "businesses"

urlpatterns = [
    path("categories", views.CategoryListView.as_view(), name="categories"),
    path("<str:slug>", views.CategoryDetailView.as_view(), name="category"),
    path(
        "<str:cat_slug>/<str:sub_slug>",
        views.SubCategoryDetailView.as_view(),
        name="subcategory",
    ),
    path(
        "<str:cat_slug>/<str:sub_slug>/<str:biz_slug>",
        views.BusinessDetailView.as_view(),
        name="business",
    ),
]

config/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("businesses/", include("businesses.urls", namespace="businesses")),
    path(
        "admin/" if settings.DEBUG else settings.ADMIN_URL,
        admin.site.urls,
    ),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("send-verification", views.send_email_verification, name="send-verification"),
    path("verify/<str:secret>", views.complete_verification, name="verify"),
    path("login/google", views.google_login, name="google-login"),
    path("login/google/callback", views.google_callback, name="google-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("profile", views.ProfileView.as_view(), name="profile"),
    path("password", views.PasswordUpdateView.as_view(), name="password"),
]

businesses/models.py
from core import models as core_models
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Category(core_models.TimeStampModel):
    name = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.name}"


class SubCategory(core_models.TimeStampModel):
    name = models.CharField(max_length=50)
    slug = models.CharField(max_length=50)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="subcategories"
    )

    class Meta:
        verbose_name_plural = "Sub categories"
        unique_together = (("category", "slug"), ("category", "name"))

    def __str__(self):
        return f"{self.name}"


def zipcode_validator(zipcode):
    try:
        assert len(zipcode) == 5
        int(zipcode)
        return zipcode
    except (AssertionError, ValueError):
        raise ValidationError("Zipcode accept only five digits")


class Business(core_models.TimeStampModel):

    BUSINESS_TYPE_OFFLINE = "offline"
    BUSINESS_TYPE_ONLINE = "online"
    BUSINESS_TYPE_BOTH = "both"
    BUSINESS_TYPE_CHOICES = (
        (BUSINESS_TYPE_OFFLINE, "Off-line"),
        (BUSINESS_TYPE_ONLINE, "Online"),
        (BUSINESS_TYPE_BOTH, "Both"),
    )

    STATE_VA = "VA"
    STATE_MD = "MD"
    STATE_DC = "DC"
    STATE_CHOICES = (
        (STATE_VA, "Virginia"),
        (STATE_MD, "Mary Land"),
        (STATE_DC, "District of Columbia"),
    )

    name_kor = models.CharField(max_length=50)
    name_eng = models.CharField(max_length=50)
    slug = models.CharField(max_length=50, unique=True)

    business_type = models.CharField(
        choices=BUSINESS_TYPE_CHOICES, max_length=20, default=BUSINESS_TYPE_OFFLINE
    )
    description = models.TextField(null=True, blank=True)

    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(choices=STATE_CHOICES, max_length=3, null=True, blank=True)
    zipcode = models.CharField(
        max_length=5, validators=[zipcode_validator], null=True, blank=True
    )
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    website = models.CharField(max_length=100, null=True, blank=True)

    is_active = models.BooleanField(default=True)

    total_rating_sum = models.IntegerField(default=0)
    total_review_count = models.IntegerField(default=0)

    subcategory = models.ForeignKey(
        SubCategory, related_name="businesses", on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        "users.User", related_name="businesses", on_delete=models.SET_NULL, null=True
    )

    class Meta:
        verbose_name_plural = "Businesses"

    def add_review(self, rating):
        self.total_review_count += 1
        self.total_rating_sum += rating
        self.save()
        return

    def average_rating(self):
        if not self.total_review_count:
            return 0
        return self.total_rating_sum / self.total_review_count


class Photo(core_models.TimeStampModel):
    file = models.ImageField(upload_to="business_photos")
    business = models.ForeignKey(
        Business, related_name="photos", on_delete=models.CASCADE
    )


class Review(core_models.TimeStampModel):
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        choices=(
            (5, "★★★★★"),
            (4, "★★★★"),
            (3, "★★★"),
            (2, "★★"),
            (1, "★"),
        ),
    )
    review = models.TextField()
    user = models.ForeignKey(
        "users.User", related_name="business_reviews", on_delete=models.CASCADE
    )
    business = models.ForeignKey(
        Business, on_delete=models.CASCADE, related_name="reviews"
    )
    is_active = models.BooleanField(default=True)


class ReplayReview(core_models.TimeStampModel):
    replay = models.TextField()
    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="replies"
    )
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name="replies")
    is_active = models.BooleanField(default=True)

businesses/forms.py
from django import forms

from . import models


class CreateReviewForm(forms.ModelForm):
    class Meta:
        model = models.Review
        fields = (
            "rating",
            "review",
        )
        labels = {"rating": "평가", "review": "리뷰"}
        widgets = {"review": forms.Textarea(attrs={"rows": 5})}

    def clean_rating(self):
        return int(self.cleaned_data.get("rating"))

    def save(self):
        return super().save(commit=False)

businesses/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView, FormView, ListView, View

from . import forms, models


class CategoryListView(ListView):
    model = models.Category
    context_object_name = "categories"


class CategoryDetailView(DetailView):
    model = models.Category


class SubCategoryDetailView(View):
    def get(self, request, cat_slug, sub_slug):
        try:
            subcategory = models.SubCategory.objects.get(
                slug=sub_slug, category__slug=cat_slug
            )
            categories = models.Category.objects.all()
        except models.SubCategory.DoesNotExist:
            raise Http404()

        return render(
            request,
            "businesses/subcategory_detail.html",
            {
                "categories": categories,
                "subcategory": subcategory,
            },
        )


class BusinessDetailView(View):
    def get(self, request, cat_slug, sub_slug, biz_slug):
        try:
            business = models.Business.objects.get(
                slug=biz_slug,
                subcategory__slug=sub_slug,
                subcategory__category__slug=cat_slug,
            )
            categories = models.Category.objects.all()
        except models.Business.DoesNotExist:
            raise Http404()

        review_form = forms.CreateReviewForm()

        return render(
            request,
            "businesses/business_detail.html",
            {
                "business": business,
                "categories": categories,
                "review_form": review_form,
            },
        )

    def post(self, request, cat_slug, sub_slug, biz_slug):
        if not request.user.nickname:
            messages.error(request, "닉네임 설정이 필요합니다")
            return redirect(reverse("users:profile"))

        try:
            business = models.Business.objects.get(
                slug=biz_slug,
                subcategory__slug=sub_slug,
                subcategory__category__slug=cat_slug,
            )
        except models.Business.DoesNotExist:
            raise Http404()

        review_form = forms.CreateReviewForm()
        action = request.POST.get("action")
        if action == "review":
            review_form = forms.CreateReviewForm(request.POST)
            if review_form.is_valid():
                review = review_form.save()
                review.user = request.user
                review.business = business
                review.save()

                business.add_review(review_form.cleaned_data.get("rating"))

        return redirect(
            reverse(
                "businesses:business",
                kwargs={
                    "cat_slug": cat_slug,
                    "sub_slug": sub_slug,
                    "biz_slug": biz_slug,
                },
            )
        )


# class BusinessDetailView(FormView):
#     form_class = forms.CreateReviewForm
#     template_name = "businesses/business_detail.html"

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         try:
#             business = models.Business.objects.get(
#                 slug=self.kwargs.get("biz_slug"),
#                 subcategory__slug=self.kwargs.get("sub_slug"),
#                 subcategory__category__slug=self.kwargs.get("cat_slug"),
#             )
#             categories = models.Category.objects.all()
#         except models.Business.DoesNotExist:
#             raise Http404()

#         context["business"] = business
#         context["categories"] = categories

#         form2 = forms.CreateReviewForm()
#         context["form2"] = form2
#         return context

#     def form_valid(self, form):
#         print("form_valid called")
#         return super().form_valid(form)

templates/businesses/business_detail.html
{% extends 'mixins/businesses/business_base.html' %}
{% load phone queryset %}

{% block title %}{{ business.name_kor }}{% endblock %}

{% block sub_content %}

<span class="text-teal-500 font-bold text-sm mb-3 inline-block"><a href="{% url 'businesses:subcategory' business.subcategory.category.slug business.subcategory.slug %}"><i class="fa-solid fa-arrow-left"></i> {{ business.subcategory.name }}</a></span>
<h1 class="font-bold text-xl">{{ business.name_kor }}</h1>
<h2 class="font-medium text-md">{{ business.name_eng }}</h2>
{% if business.total_review_count %}
    {% include 'mixins/businesses/rating_star.html' with average_rating=business.average_rating %}
{% endif %}

<hr>
{% if business.description %}
    {{ business.description }}
{% else %}
<div class="text-sm text-center font-bold">
    비지니스 상세페이지를 바꾸시고 싶으면 신청해주세요
</div>
{% endif %}

<hr>
{% if user.is_authenticated and user.nickname %}
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="action" value="review" />
    <div class="flex flex-col md:flex-row gap-4">
        <div class="basis-1/4 shrink-0">
            {{ review_form.rating.label_tag }}
            <div class="text-green-600">{{ review_form.rating }}</div>
        </div>
        <div class="grow">
            {{ review_form.review.label_tag }}
            {{ review_form.review }}
        </div>
    </div>
    <div class="text-right">
        <button class="rounded font-bold text-sm px-4 py-1 bg-blue-700 text-white">남기기</button>
    </div>
</form>
{% elif user.is_authenticated and not user.nickname %}
<div class="text-center text-sm font-bold">
    <a href="{% url 'users:profile' %}?next={{ request.path }}">리뷰를 남기시려면 닉네임을 설정해주세요</a>
</div>
{% else %}
<div class="text-center text-sm font-bold">
    <a href="{% url 'users:login' %}?next={{ request.path }}">로그인하고 리뷰남기기</a>
</div>
{% endif %}

<h3 class="font-bold text-lg">리뷰 ({{ business.reviews.count }})</h3>
<div>
    {% for review in business.reviews.all|order_by:'-pk' %}
    <div class="flex flex-col md:flex-row gap-4 py-4 border-y">
        <div class="basis-1/4 shrink-0">
            <div>{{ review.user.nickname }}</div>
            <div class="text-sm text-gray-400 font-medium">{{ review.created }}</div>
            <div>{% include 'mixins/businesses/rating_star.html' with average_rating=review.rating %}</div>
        </div>
        <div>
            <p>{{ review.review }}</p>
        </div>
    </div>
    {% endfor %}
</div>


<div class="fixed left-0 top-1/2 lg:hidden z-10">
    <a href="{% url 'businesses:subcategory' business.subcategory.category.slug business.subcategory.slug %}" class="rounded-r-lg bg-green-300 font-bold text-sm py-8 px-1"><i class="fa-solid fa-arrow-right-from-bracket"></i></a>
</div>
{% endblock %}

templates/businesses/category_detail.html
{% extends 'base.html' %}

{% block title %}{{ category.name }}{% endblock %}


{% block content %}
    <div class="w-full md:w-1/2 lg:w-1/3 mx-auto">
        <a href="{% url 'businesses:categories' %}"><h5 class="mb-3 text-teal-600 font-bold"><i class="fa-solid fa-arrow-left"></i> 전체 카테고리</h5></a>
        {% include 'mixins/businesses/category_box.html' with category=category %}
    </div>
{% endblock %}

templates/businesses/category_list.html
{% extends 'base.html' %}

{% block title %}한인업소록{% endblock %}

{% block content %}
    
    <div class="grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
        {% for category in categories %}
            {% include 'mixins/businesses/category_box.html' with category=category %}
        {% endfor %}
    </div>
{% endblock %}

templates/businesses/subcategory_detail.html
{% extends 'mixins/businesses/business_base.html' %}
{% load phone queryset %}

{% block title %}{{ subcategory.name }}{% endblock %}

{% block sub_content %}

<h1 class="mb-4">
    <span class="text-sm font-bold text-gray-400">{{ subcategory.category.name }}</span>
    <span class="text-lg font-bold ml-4">{{ subcategory.name }}</span>
</h1>

<div class="grid grid-cols-1 md:grid-cols-2 gap-3">
{% for business in subcategory.businesses.all|order_by:"-total_review_count,-total_rating_sum,name_kor,name_eng" %}
    <div class="p-5 shadow rounded">
        <a href="{% url 'businesses:business' subcategory.category.slug subcategory.slug business.slug %}">
            <div class="font-bold text-md">{{ business.name_kor }}</div>
            <div class="font-medium text-sm">{{ business.name_eng }}</div>
        </a>

        <div class="flex items-center mt-2">
            <i class="fa-solid fa-location-dot"></i>
            <div class="ml-2">
                {{ business.address }} {{ business.city }}, {{ business.state }} {{ business.zipcode }}
            </div>
        </div>
        <div class="flex items-center">
            <i class="fa-solid fa-phone"></i>
            <div class="ml-2">
                {{ business.phone_number|phone }}
            </div>
        </div>
        <hr class="my-2">
        <a href="{% url 'businesses:business' subcategory.category.slug subcategory.slug business.slug %}">
            <div class="flex justify-between font-medium">
                {% if business.total_review_count %}
                    {% include 'mixins/businesses/rating_star.html' with average_rating=business.average_rating %}
                {% endif %}
                <div>
                    {{ business.total_review_count }} Reviews
                </div>
            </div>
        </a>
    </div>
{% endfor %}
</div>


<div class="fixed left-0 top-1/2 lg:hidden z-10">
    <a href="{% url 'businesses:categories' %}" class="rounded-r-lg bg-green-300 font-bold text-sm py-8 px-1"><i class="fa-solid fa-arrow-right-from-bracket"></i></a>
</div>

{% endblock %}